# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - funlen
    - lll
    - tenv
