// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_key

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KeyDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"actions": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"collections": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Required: true,
			},
			"value": schema.StringAttribute{
				Optional:  true,
				Computed:  true,
				Sensitive: true,
			},
			"value_prefix": schema.StringAttribute{
				Computed: true,
			},
		},
		Description: "Typesense Key",
	}
}

type KeyModel struct {
	Actions     types.List   `tfsdk:"actions"`
	Collections types.List   `tfsdk:"collections"`
	Description types.String `tfsdk:"description"`
	Id          types.Int64  `tfsdk:"id"`
	Value       types.String `tfsdk:"value"`
	ValuePrefix types.String `tfsdk:"value_prefix"`
}
