// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_typesense

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func TypesenseProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				Optional:            true,
				Description:         "Typesense Admin API Key. Alternatively, can be configured using the `TYPESENSE_API_KEY` environment variable.",
				MarkdownDescription: "Typesense Admin API Key. Alternatively, can be configured using the `TYPESENSE_API_KEY` environment variable.",
			},
			"url": schema.StringAttribute{
				Optional:            true,
				Description:         "Typesense API URL. Alternatively, can be configured using the `TYPESENSE_URL` environment variable. Alternatively alternatively, can be configured using the `TYPESENSE_PROTOCOL`, `TYPESENSE_HOST` and `TYPESENSE_PORT` environment variables.",
				MarkdownDescription: "Typesense API URL. Alternatively, can be configured using the `TYPESENSE_URL` environment variable. Alternatively alternatively, can be configured using the `TYPESENSE_PROTOCOL`, `TYPESENSE_HOST` and `TYPESENSE_PORT` environment variables.",
			},
		},
	}
}

type TypesenseModel struct {
	ApiKey types.String `tfsdk:"api_key"`
	Url    types.String `tfsdk:"url"`
}
