// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_typesense

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func TypesenseProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				Optional: true,
			},
			"url": schema.StringAttribute{
				Optional: true,
			},
		},
	}
}

type TypesenseModel struct {
	ApiKey types.String `tfsdk:"api_key"`
	Url    types.String `tfsdk:"url"`
}
