// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_keys

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KeysDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"keys": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"actions": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"collections": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"description": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"value": schema.StringAttribute{
							Optional:  true,
							Computed:  true,
							Sensitive: true,
						},
						"value_prefix": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: KeysType{
						ObjectType: types.ObjectType{
							AttrTypes: KeysValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type KeysModel struct {
	Keys types.List `tfsdk:"keys"`
}

var _ basetypes.ObjectTypable = KeysType{}

type KeysType struct {
	basetypes.ObjectType
}

func (t KeysType) Equal(o attr.Type) bool {
	other, ok := o.(KeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t KeysType) String() string {
	return "KeysType"
}

func (t KeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	actionsAttribute, ok := attributes["actions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`actions is missing from object`)

		return nil, diags
	}

	actionsVal, ok := actionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`actions expected to be basetypes.ListValue, was: %T`, actionsAttribute))
	}

	collectionsAttribute, ok := attributes["collections"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`collections is missing from object`)

		return nil, diags
	}

	collectionsVal, ok := collectionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`collections expected to be basetypes.ListValue, was: %T`, collectionsAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	valuePrefixAttribute, ok := attributes["value_prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value_prefix is missing from object`)

		return nil, diags
	}

	valuePrefixVal, ok := valuePrefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value_prefix expected to be basetypes.StringValue, was: %T`, valuePrefixAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return KeysValue{
		Actions:     actionsVal,
		Collections: collectionsVal,
		Description: descriptionVal,
		Id:          idVal,
		Value:       valueVal,
		ValuePrefix: valuePrefixVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewKeysValueNull() KeysValue {
	return KeysValue{
		state: attr.ValueStateNull,
	}
}

func NewKeysValueUnknown() KeysValue {
	return KeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (KeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing KeysValue Attribute Value",
				"While creating a KeysValue value, a missing attribute value was detected. "+
					"A KeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid KeysValue Attribute Type",
				"While creating a KeysValue value, an invalid attribute value was detected. "+
					"A KeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("KeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra KeysValue Attribute Value",
				"While creating a KeysValue value, an extra attribute value was detected. "+
					"A KeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra KeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	actionsAttribute, ok := attributes["actions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`actions is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	actionsVal, ok := actionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`actions expected to be basetypes.ListValue, was: %T`, actionsAttribute))
	}

	collectionsAttribute, ok := attributes["collections"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`collections is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	collectionsVal, ok := collectionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`collections expected to be basetypes.ListValue, was: %T`, collectionsAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	valuePrefixAttribute, ok := attributes["value_prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value_prefix is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	valuePrefixVal, ok := valuePrefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value_prefix expected to be basetypes.StringValue, was: %T`, valuePrefixAttribute))
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	return KeysValue{
		Actions:     actionsVal,
		Collections: collectionsVal,
		Description: descriptionVal,
		Id:          idVal,
		Value:       valueVal,
		ValuePrefix: valuePrefixVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) KeysValue {
	object, diags := NewKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t KeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewKeysValueMust(KeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t KeysType) ValueType(ctx context.Context) attr.Value {
	return KeysValue{}
}

var _ basetypes.ObjectValuable = KeysValue{}

type KeysValue struct {
	Actions     basetypes.ListValue   `tfsdk:"actions"`
	Collections basetypes.ListValue   `tfsdk:"collections"`
	Description basetypes.StringValue `tfsdk:"description"`
	Id          basetypes.Int64Value  `tfsdk:"id"`
	Value       basetypes.StringValue `tfsdk:"value"`
	ValuePrefix basetypes.StringValue `tfsdk:"value_prefix"`
	state       attr.ValueState
}

func (v KeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["actions"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["collections"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["value_prefix"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Actions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["actions"] = val

		val, err = v.Collections.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["collections"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		val, err = v.ValuePrefix.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value_prefix"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v KeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v KeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v KeysValue) String() string {
	return "KeysValue"
}

func (v KeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	actionsVal, d := types.ListValue(types.StringType, v.Actions.Elements())

	diags.Append(d...)

	if d.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"actions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"collections": basetypes.ListType{
				ElemType: types.StringType,
			},
			"description":  basetypes.StringType{},
			"id":           basetypes.Int64Type{},
			"value":        basetypes.StringType{},
			"value_prefix": basetypes.StringType{},
		}), diags
	}

	collectionsVal, d := types.ListValue(types.StringType, v.Collections.Elements())

	diags.Append(d...)

	if d.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"actions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"collections": basetypes.ListType{
				ElemType: types.StringType,
			},
			"description":  basetypes.StringType{},
			"id":           basetypes.Int64Type{},
			"value":        basetypes.StringType{},
			"value_prefix": basetypes.StringType{},
		}), diags
	}

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"actions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"collections": basetypes.ListType{
				ElemType: types.StringType,
			},
			"description":  basetypes.StringType{},
			"id":           basetypes.Int64Type{},
			"value":        basetypes.StringType{},
			"value_prefix": basetypes.StringType{},
		},
		map[string]attr.Value{
			"actions":      actionsVal,
			"collections":  collectionsVal,
			"description":  v.Description,
			"id":           v.Id,
			"value":        v.Value,
			"value_prefix": v.ValuePrefix,
		})

	return objVal, diags
}

func (v KeysValue) Equal(o attr.Value) bool {
	other, ok := o.(KeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Actions.Equal(other.Actions) {
		return false
	}

	if !v.Collections.Equal(other.Collections) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	if !v.ValuePrefix.Equal(other.ValuePrefix) {
		return false
	}

	return true
}

func (v KeysValue) Type(ctx context.Context) attr.Type {
	return KeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v KeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"actions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"collections": basetypes.ListType{
			ElemType: types.StringType,
		},
		"description":  basetypes.StringType{},
		"id":           basetypes.Int64Type{},
		"value":        basetypes.StringType{},
		"value_prefix": basetypes.StringType{},
	}
}
