// Code generated by ogen, DO NOT EDIT.
package typesense

type CreateAnalyticsEventRes interface {
	createAnalyticsEventRes()
}

type CreateAnalyticsRuleRes interface {
	createAnalyticsRuleRes()
}

type CreateCollectionRes interface {
	createCollectionRes()
}

type CreateConversationModelRes interface {
	createConversationModelRes()
}

type CreateKeyRes interface {
	createKeyRes()
}

type CreateNLSearchModelRes interface {
	createNLSearchModelRes()
}

type DeleteAliasRes interface {
	deleteAliasRes()
}

type DeleteAnalyticsRuleRes interface {
	deleteAnalyticsRuleRes()
}

type DeleteCollectionRes interface {
	deleteCollectionRes()
}

type DeleteDocumentRes interface {
	deleteDocumentRes()
}

type DeleteDocumentsRes interface {
	deleteDocumentsRes()
}

type DeleteKeyRes interface {
	deleteKeyRes()
}

type DeleteNLSearchModelRes interface {
	deleteNLSearchModelRes()
}

type DeletePresetRes interface {
	deletePresetRes()
}

type DeleteSearchOverrideRes interface {
	deleteSearchOverrideRes()
}

type DeleteSearchSynonymRes interface {
	deleteSearchSynonymRes()
}

type DeleteStopwordsSetRes interface {
	deleteStopwordsSetRes()
}

type ExportDocumentsRes interface {
	exportDocumentsRes()
}

type GetAliasRes interface {
	getAliasRes()
}

type GetCollectionRes interface {
	getCollectionRes()
}

type GetDocumentRes interface {
	getDocumentRes()
}

type GetKeyRes interface {
	getKeyRes()
}

type GetSearchSynonymRes interface {
	getSearchSynonymRes()
}

type GetSearchSynonymsRes interface {
	getSearchSynonymsRes()
}

type GetStemmingDictionaryRes interface {
	getStemmingDictionaryRes()
}

type ImportDocumentsRes interface {
	importDocumentsRes()
}

type ImportStemmingDictionaryRes interface {
	importStemmingDictionaryRes()
}

type IndexDocumentRes interface {
	indexDocumentRes()
}

type MultiSearchRes interface {
	multiSearchRes()
}

type RetrieveAnalyticsRuleRes interface {
	retrieveAnalyticsRuleRes()
}

type RetrieveNLSearchModelRes interface {
	retrieveNLSearchModelRes()
}

type RetrievePresetRes interface {
	retrievePresetRes()
}

type RetrieveStopwordsSetRes interface {
	retrieveStopwordsSetRes()
}

type SearchCollectionRes interface {
	searchCollectionRes()
}

type UpdateCollectionRes interface {
	updateCollectionRes()
}

type UpdateDocumentRes interface {
	updateDocumentRes()
}

type UpdateDocumentsRes interface {
	updateDocumentsRes()
}

type UpdateNLSearchModelRes interface {
	updateNLSearchModelRes()
}

type UpsertAliasRes interface {
	upsertAliasRes()
}

type UpsertAnalyticsRuleRes interface {
	upsertAnalyticsRuleRes()
}

type UpsertPresetRes interface {
	upsertPresetRes()
}

type UpsertSearchOverrideRes interface {
	upsertSearchOverrideRes()
}

type UpsertSearchSynonymRes interface {
	upsertSearchSynonymRes()
}

type UpsertStopwordsSetRes interface {
	upsertStopwordsSetRes()
}
