// Code generated by ogen, DO NOT EDIT.

package typesense

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAPIKeyHeader handles api_key_header security.
	HandleAPIKeyHeader(ctx context.Context, operationName OperationName, t APIKeyHeader) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesAPIKeyHeader = map[string][]string{
	CreateKeyOperation: []string{},
	DeleteKeyOperation: []string{},
	GetKeyOperation:    []string{},
	GetKeysOperation:   []string{},
}

func (s *Server) securityAPIKeyHeader(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t APIKeyHeader
	const parameterName = "X-TYPESENSE-API-KEY"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesAPIKeyHeader[operationName]
	rctx, err := s.sec.HandleAPIKeyHeader(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// APIKeyHeader provides api_key_header security value.
	APIKeyHeader(ctx context.Context, operationName OperationName, client *Client) (APIKeyHeader, error)
}

func (s *Client) securityAPIKeyHeader(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.APIKeyHeader(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"APIKeyHeader\"")
	}
	req.Header.Set("X-TYPESENSE-API-KEY", t.APIKey)
	return nil
}
