// Code generated by ogen, DO NOT EDIT.

package typesense

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAPIKeyHeader handles api_key_header security.
	HandleAPIKeyHeader(ctx context.Context, operationName OperationName, t APIKeyHeader) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesAPIKeyHeader = map[string][]string{
	CreateAnalyticsEventOperation:          []string{},
	CreateAnalyticsRuleOperation:           []string{},
	CreateCollectionOperation:              []string{},
	CreateConversationModelOperation:       []string{},
	CreateKeyOperation:                     []string{},
	CreateNLSearchModelOperation:           []string{},
	DebugOperation:                         []string{},
	DeleteAliasOperation:                   []string{},
	DeleteAnalyticsRuleOperation:           []string{},
	DeleteCollectionOperation:              []string{},
	DeleteConversationModelOperation:       []string{},
	DeleteDocumentOperation:                []string{},
	DeleteDocumentsOperation:               []string{},
	DeleteKeyOperation:                     []string{},
	DeleteNLSearchModelOperation:           []string{},
	DeletePresetOperation:                  []string{},
	DeleteSearchOverrideOperation:          []string{},
	DeleteSearchSynonymOperation:           []string{},
	DeleteStopwordsSetOperation:            []string{},
	ExportDocumentsOperation:               []string{},
	GetAliasOperation:                      []string{},
	GetAliasesOperation:                    []string{},
	GetCollectionOperation:                 []string{},
	GetCollectionsOperation:                []string{},
	GetDocumentOperation:                   []string{},
	GetKeyOperation:                        []string{},
	GetKeysOperation:                       []string{},
	GetSchemaChangesOperation:              []string{},
	GetSearchOverrideOperation:             []string{},
	GetSearchOverridesOperation:            []string{},
	GetSearchSynonymOperation:              []string{},
	GetSearchSynonymsOperation:             []string{},
	GetStemmingDictionaryOperation:         []string{},
	HealthOperation:                        []string{},
	ImportDocumentsOperation:               []string{},
	ImportStemmingDictionaryOperation:      []string{},
	IndexDocumentOperation:                 []string{},
	ListStemmingDictionariesOperation:      []string{},
	MultiSearchOperation:                   []string{},
	RetrieveAPIStatsOperation:              []string{},
	RetrieveAllConversationModelsOperation: []string{},
	RetrieveAllNLSearchModelsOperation:     []string{},
	RetrieveAllPresetsOperation:            []string{},
	RetrieveAnalyticsRuleOperation:         []string{},
	RetrieveAnalyticsRulesOperation:        []string{},
	RetrieveConversationModelOperation:     []string{},
	RetrieveMetricsOperation:               []string{},
	RetrieveNLSearchModelOperation:         []string{},
	RetrievePresetOperation:                []string{},
	RetrieveStopwordsSetOperation:          []string{},
	RetrieveStopwordsSetsOperation:         []string{},
	SearchCollectionOperation:              []string{},
	TakeSnapshotOperation:                  []string{},
	UpdateCollectionOperation:              []string{},
	UpdateConversationModelOperation:       []string{},
	UpdateDocumentOperation:                []string{},
	UpdateDocumentsOperation:               []string{},
	UpdateNLSearchModelOperation:           []string{},
	UpsertAliasOperation:                   []string{},
	UpsertAnalyticsRuleOperation:           []string{},
	UpsertPresetOperation:                  []string{},
	UpsertSearchOverrideOperation:          []string{},
	UpsertSearchSynonymOperation:           []string{},
	UpsertStopwordsSetOperation:            []string{},
	VoteOperation:                          []string{},
}

func (s *Server) securityAPIKeyHeader(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t APIKeyHeader
	const parameterName = "X-TYPESENSE-API-KEY"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesAPIKeyHeader[operationName]
	rctx, err := s.sec.HandleAPIKeyHeader(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// APIKeyHeader provides api_key_header security value.
	APIKeyHeader(ctx context.Context, operationName OperationName, client *Client) (APIKeyHeader, error)
}

func (s *Client) securityAPIKeyHeader(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.APIKeyHeader(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"APIKeyHeader\"")
	}
	req.Header.Set("X-TYPESENSE-API-KEY", t.APIKey)
	return nil
}
