// Code generated by ogen, DO NOT EDIT.

package typesense

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteKeyParams is parameters of deleteKey operation.
type DeleteKeyParams struct {
	// The ID of the key to delete.
	KeyId int64
}

func unpackDeleteKeyParams(packed middleware.Parameters) (params DeleteKeyParams) {
	{
		key := middleware.ParameterKey{
			Name: "keyId",
			In:   "path",
		}
		params.KeyId = packed[key].(int64)
	}
	return params
}

func decodeDeleteKeyParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteKeyParams, _ error) {
	// Decode path: keyId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "keyId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.KeyId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "keyId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetKeyParams is parameters of getKey operation.
type GetKeyParams struct {
	// The ID of the key to retrieve.
	KeyId int64
}

func unpackGetKeyParams(packed middleware.Parameters) (params GetKeyParams) {
	{
		key := middleware.ParameterKey{
			Name: "keyId",
			In:   "path",
		}
		params.KeyId = packed[key].(int64)
	}
	return params
}

func decodeGetKeyParams(args [1]string, argsEscaped bool, r *http.Request) (params GetKeyParams, _ error) {
	// Decode path: keyId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "keyId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.KeyId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "keyId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
