// Code generated by ogen, DO NOT EDIT.

package typesense

type APIKeyHeader struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *APIKeyHeader) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *APIKeyHeader) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *APIKeyHeader) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *APIKeyHeader) SetRoles(val []string) {
	s.Roles = val
}

// Merged schema.
// Ref: #/components/schemas/ApiKey
type ApiKey struct {
	Value       OptString `json:"value"`
	Description string    `json:"description"`
	Actions     []string  `json:"actions"`
	Collections []string  `json:"collections"`
	ExpiresAt   OptInt64  `json:"expires_at"`
	ID          OptInt64  `json:"id"`
	ValuePrefix OptString `json:"value_prefix"`
}

// GetValue returns the value of Value.
func (s *ApiKey) GetValue() OptString {
	return s.Value
}

// GetDescription returns the value of Description.
func (s *ApiKey) GetDescription() string {
	return s.Description
}

// GetActions returns the value of Actions.
func (s *ApiKey) GetActions() []string {
	return s.Actions
}

// GetCollections returns the value of Collections.
func (s *ApiKey) GetCollections() []string {
	return s.Collections
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *ApiKey) GetExpiresAt() OptInt64 {
	return s.ExpiresAt
}

// GetID returns the value of ID.
func (s *ApiKey) GetID() OptInt64 {
	return s.ID
}

// GetValuePrefix returns the value of ValuePrefix.
func (s *ApiKey) GetValuePrefix() OptString {
	return s.ValuePrefix
}

// SetValue sets the value of Value.
func (s *ApiKey) SetValue(val OptString) {
	s.Value = val
}

// SetDescription sets the value of Description.
func (s *ApiKey) SetDescription(val string) {
	s.Description = val
}

// SetActions sets the value of Actions.
func (s *ApiKey) SetActions(val []string) {
	s.Actions = val
}

// SetCollections sets the value of Collections.
func (s *ApiKey) SetCollections(val []string) {
	s.Collections = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *ApiKey) SetExpiresAt(val OptInt64) {
	s.ExpiresAt = val
}

// SetID sets the value of ID.
func (s *ApiKey) SetID(val OptInt64) {
	s.ID = val
}

// SetValuePrefix sets the value of ValuePrefix.
func (s *ApiKey) SetValuePrefix(val OptString) {
	s.ValuePrefix = val
}

func (*ApiKey) createKeyRes() {}
func (*ApiKey) getKeyRes()    {}

// Ref: #/components/schemas/ApiKeyDeleteResponse
type ApiKeyDeleteResponse struct {
	// The id of the API key that was deleted.
	ID int64 `json:"id"`
}

// GetID returns the value of ID.
func (s *ApiKeyDeleteResponse) GetID() int64 {
	return s.ID
}

// SetID sets the value of ID.
func (s *ApiKeyDeleteResponse) SetID(val int64) {
	s.ID = val
}

func (*ApiKeyDeleteResponse) deleteKeyRes() {}

// Ref: #/components/schemas/ApiKeySchema
type ApiKeySchema struct {
	Value       OptString `json:"value"`
	Description string    `json:"description"`
	Actions     []string  `json:"actions"`
	Collections []string  `json:"collections"`
	ExpiresAt   OptInt64  `json:"expires_at"`
}

// GetValue returns the value of Value.
func (s *ApiKeySchema) GetValue() OptString {
	return s.Value
}

// GetDescription returns the value of Description.
func (s *ApiKeySchema) GetDescription() string {
	return s.Description
}

// GetActions returns the value of Actions.
func (s *ApiKeySchema) GetActions() []string {
	return s.Actions
}

// GetCollections returns the value of Collections.
func (s *ApiKeySchema) GetCollections() []string {
	return s.Collections
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *ApiKeySchema) GetExpiresAt() OptInt64 {
	return s.ExpiresAt
}

// SetValue sets the value of Value.
func (s *ApiKeySchema) SetValue(val OptString) {
	s.Value = val
}

// SetDescription sets the value of Description.
func (s *ApiKeySchema) SetDescription(val string) {
	s.Description = val
}

// SetActions sets the value of Actions.
func (s *ApiKeySchema) SetActions(val []string) {
	s.Actions = val
}

// SetCollections sets the value of Collections.
func (s *ApiKeySchema) SetCollections(val []string) {
	s.Collections = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *ApiKeySchema) SetExpiresAt(val OptInt64) {
	s.ExpiresAt = val
}

// Ref: #/components/schemas/ApiKeysResponse
type ApiKeysResponse struct {
	Keys []ApiKey `json:"keys"`
}

// GetKeys returns the value of Keys.
func (s *ApiKeysResponse) GetKeys() []ApiKey {
	return s.Keys
}

// SetKeys sets the value of Keys.
func (s *ApiKeysResponse) SetKeys(val []ApiKey) {
	s.Keys = val
}

// Ref: #/components/schemas/ApiResponse
type ApiResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ApiResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ApiResponse) SetMessage(val string) {
	s.Message = val
}

func (*ApiResponse) getKeyRes() {}

type CreateKeyBadRequest ApiResponse

func (*CreateKeyBadRequest) createKeyRes() {}

type CreateKeyConflict ApiResponse

func (*CreateKeyConflict) createKeyRes() {}

type DeleteKeyBadRequest ApiResponse

func (*DeleteKeyBadRequest) deleteKeyRes() {}

type DeleteKeyNotFound ApiResponse

func (*DeleteKeyNotFound) deleteKeyRes() {}

// NewOptApiKeySchema returns new OptApiKeySchema with value set to v.
func NewOptApiKeySchema(v ApiKeySchema) OptApiKeySchema {
	return OptApiKeySchema{
		Value: v,
		Set:   true,
	}
}

// OptApiKeySchema is optional ApiKeySchema.
type OptApiKeySchema struct {
	Value ApiKeySchema
	Set   bool
}

// IsSet returns true if OptApiKeySchema was set.
func (o OptApiKeySchema) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptApiKeySchema) Reset() {
	var v ApiKeySchema
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptApiKeySchema) SetTo(v ApiKeySchema) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptApiKeySchema) Get() (v ApiKeySchema, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptApiKeySchema) Or(d ApiKeySchema) ApiKeySchema {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
