// Code generated by ogen, DO NOT EDIT.

package typesense

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateKeyOperation OperationName = "CreateKey"
	DeleteKeyOperation OperationName = "DeleteKey"
	GetKeyOperation    OperationName = "GetKey"
	GetKeysOperation   OperationName = "GetKeys"
)
