name: update indirect dependencies

on:
  schedule:
    - cron: "15 9 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - id: cyspbot
        uses: chikachow/cyspbot-app-token-action@8894f93a0c17b5a160dafa8df13a46c0399f80a8 # v0.0.4
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: update indirect dependencies
        run: for x in $(go list -f '{{if .Indirect}}{{.Path}}{{end}}' -m all); do go get -u "$x"; done || true

      - name: go mod tidy
        run: go mod tidy -v

      - name: create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.cyspbot.outputs.token }}
          commit-message: "chore(deps): bump indirect dependencies"
          title: "chore(deps): bump indirect dependencies"
          branch: "github-action-update-indirect-dependencies"
          body: ''
          sign-commits: true
